pipeline {
  agent none
  stages {
    stage('Docker Build') {
      agent { label 'Master' }
      steps {
        sh 'chmod 777 -R ${WORKSPACE}/bulletin-board-app'
        sh 'sudo docker build -t vikson36/bb-app:${BUILD_NUMBER} ${WORKSPACE}/bulletin-board-app'
      }
    }
	  
    stage('Docker Push') {
      agent { label 'Master' }
      steps {
        sh 'sudo docker push vikson36/bb-app:latest'
      }
    }  
}
	
}
