pipeline {
  agent none
  stages {
    stage('Docker Build') {
      agent { label 'Master' }
      steps {
        sh 'chmod 777 -R ${WORKSPACE}/bulletin-board-app'
        sh 'sudo docker build -t vikson36/bb-app:latest ${WORKSPACE}/bulletin-board-app'
      }
    }
	  
    stage('Docker Push') {
      agent { label 'Master' }
      steps {
        sh 'sudo docker push vikson36/bb-app:latest'
      }
    }  
    stage('Docker pull') {
      agent { label 'Master' }
      steps {
	
        sh 'sudo docker pull vikson36/bb-app:latest'
      }
    }
	  
    stage('Docker Stop') {
      agent { label 'Master' }
      steps {
	sh 'sudo docker stop $(docker ps -a -q)'
        sh ('docker rm $(docker ps -a -q)')
      }
    }
	  
   stage('Docker run') {
      agent { label 'Master' }
      steps {
        sh 'sudo docker container run --detach --publish 8080:8080 vikson36/bb-app:latest'
      }
    }
	  
	  
}
	
}
